language:
  - objective-c

env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=matplotlib-test-results
    - secure: RTMoQnCFDKYyDniegep9nARI5bKroF1TpN/aQf02KwLia0z5IZ4eoiFxTufexgB2afXtpAa2LDZg2+ulD9+SZQ+h7GHibMEVpcOTv4ojy+ekiRAQ6OW9glrcidFoIfISJNrrNZL7mTC6baEhnjjsH0mErpBTcfZSpFpLOSNjpSs=
    - secure: uxYSxs3D3ZOTNjRg0vKk1YsOpG5vWshekMixV4lEuwcSnLJtNHUhZvzoj11GLwqHokTaYXlM1TvFMm7oQBwtW5B+dacnOFar3MJlvu96n+B1CG6ldiIy4uZd+DKR7la0vwK7aTOKyiMK+vWQe8C0kCYBTcN0UiVQn/2nUlFgioM=

  matrix:
    - INSTALL_TYPE=macpython VERSION=2.7.6

before_script:
    # This seems to be broken at the moment
    # - gem install travis-artifacts

install:
  - set -vx  # echo commands
  - git clone http://github.com/matplotlib/matplotlib.git
  - cd matplotlib
  - git checkout master
  - git log -n 1
  - cd ..
  - source ./travis_install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh

after_failure:
    - echo $PWD
    # - ../travis_upload.sh
